[General]
# Valid values are Dummy, HD44780, LCDproc, Nextion, OLED, TFTSurenoo
Display=OLED
TemperatureInF=0
Daemon=0

[Log]
# Logging levels, 0=No logging
MQTTLevel=1
DisplayLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Keepalive=60
Auth=0
Username=mmdvm
Password=mmdvm
Name=display
HostMQTTName=host
InfoMQTTName=info
HostConfName=MMDVM-Host

[OLED]
# 3 = SSD1306 128x64 I2C (0x3C), 6 = SH1106 128x64 I2C
Type=3
Brightness=0
Invert=0
Scroll=1
Rotate=0
Cast=0
LogoScreensaver=1
