[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Address=127.0.0.1
Port=1883
Keepalive=60
Name=info
Auth=0
Username=mmdvm
Password=mmdvm

[Exclude]
# Не отдавать секреты в MQTT
Key=Password
Key=AuthKey

[Configs]
MMDVM-Host=/etc/MMDVMHost/mmdvmhost.cfg
DMRGateway=/etc/DMRGateway/dmrgateway.cfg

[Programs]
Refresh=60
Program=DMRGateway
Program=MMDVMHost

[CPU]
Refresh=60
